[package]
name = "futures-signals"
version = "0.1.0"
authors = ["Pauan <pcxunlimited@gmail.com>"]
description = "Zero cost FRP signals using the futures crate"
repository = "https://github.com/Pauan/rust-signals"
homepage = "https://github.com/Pauan/rust-signals"
readme = "README.md"
license = "MIT"
keywords = ["signal", "reactive", "frp", "futures"]
categories = ["asynchronous"]

[dependencies]
futures-core = "0.2.0-beta"
futures-channel = "0.2.0-beta"
futures-executor = "0.2.0-beta"
futures-util = "0.2.0-beta"
discard = "1.0.3"
# TODO make this optional
serde = "1.0.27"
